### ISSUE TITLE
IOException is thrown while running tests

### ISSUE THREAD

**Issue by gigatsiklauri** [gmamaladze/FreeUni-SDP-2015-Lab-Realization#65]
<pre><code>java.io.IOException
at ge.edu.freeuni.sdp.snake.model.HighScoreData.readFile(HighScoreData.java:41)
at ge.edu.freeuni.sdp.snake.model.HighScoreDataTest.testReadDirtyFile(HighScoreDataTest.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
java.io.IOException
at ge.edu.freeuni.sdp.snake.model.HighScoreData.writeToFile(HighScoreData.java:94)
at ge.edu.freeuni.sdp.snake.model.HighScoreData.editFile(HighScoreData.java:120)
at ge.edu.freeuni.sdp.snake.model.HighScoreDataTest.testFileEdit_2(HighScoreDataTest.java:176)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
</code></pre>

**Comment by berolomsa** [comment]
მგონი ეს შენი პრობლემაა აბა Travis-Ci თუ ბილდავს ე.ი ყველაფერი მუშაობს. highscore.txt ფაილი არ გექნება ალბათ მაგიტო

**Comment by gigatsiklauri** [comment]
მაქვს აშკარად ეგ ფაილი
(თან თუ არ არსებობს თავისით არ უნდა ქმნიდეს?)
[Imgur](http://i.imgur.com/EzdIOw8.png?1)

**Comment by gmamaladze** [comment]
File io  იუნიტ ტესტებში ზოგადად დაუშვებელია.
ეს როგორც ლექციაზე ასევე სემინარზე გქონდათ.
ზოგი თქვენი თანაკურსელი დროზე მიხვდა და რეალურ ფაილებთან მუშაობა მოკებზე გადააკეთა. იხ. https://piazza.com/class/i6qspctxmm86bt?cid=69

IO პრობლემები ტესტებში, რეალურ ფაილებთან მუშაობისას ძალიან ტიპიურია და ძალიან ალბათია. ანუ პრობლემა კონკრეტული ფაილის ყოფნა არ ყოფნასა თუ ტესტის ან კოდის სისწორეში არაა. პრობლემა იმაშია რომ File IO-ს მოკი არ დაიწერა.
